name: IPFS

on:
  push:
    branches:
      - master
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aquiladev/ipfs-action@v0.2.1
        id: upload
        env:
          PINATA_KEY: ${{ secrets.PINATA_KEY }}
          PINATA_SECRET: ${{ secrets.PINATA_SECRET }}
        with:
          path: ./
          pinataKey: $PINATA_KEY
          pinataSecret: $PINATA_SECRET
          pinataPinName: "ipns.q9f.cc.${{ github.sha }}"
